version: "3.6"
services:
 wordpress:
   image: wordpress:latest
   container_name: wordcamp
   volumes:
     - ./wordpress:/var/www/html
     - ./plugins:/var/www/html/wp-content/plugins

   environment:
     - WORDPRESS_DB_NAME=wordpress
     - WORDPRESS_TABLE_PREFIX=wp_
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=password
   depends_on:
     - db
   restart: always
   ports:
     - 3000:80
 
 db:
   image: mariadb:latest
   container_name: wordcamp-db
   volumes:
     - db_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=root
     - MYSQL_PASSWORD=password
     - MYSQL_DATABASE=wordpress
   restart: always
 
volumes:
 db_data:
